// Index generator: derives project/map/index.yaml + project/status.md from the map.
// Never hand-written. Run after any map change; verify checks it is fresh.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { loadModel, buildGraph, hashMap } from './lib.mjs';

function rollup(nodes, predicate) {
  const r = { implemented: 0, partial: 0, planned: 0, deferred: 0 };
  for (const n of nodes) {
    if (!predicate(n)) continue;
    const s = n.status || 'implemented';
    if (r[s] === undefined) r[s] = 0;
    r[s] += 1;
  }
  return r;
}

export function generateIndex(projectDir) {
  const model = loadModel(projectDir);
  const graph = buildGraph(model);
  const all = [...model.nodes.values()];

  const byKind = (k) => all.filter((n) => n.kind === k);
  const totals = {};
  for (const n of all) totals[n.kind] = (totals[n.kind] || 0) + 1;

  const status_rollup = {};
  for (const k of Object.keys(totals)) {
    status_rollup[k] = rollup(all, (n) => n.kind === k);
  }

  // Compact graph: only nodes that have edges or are pointed at.
  const graphOut = {};
  for (const [id, node] of model.nodes) {
    const g = graph.get(id) || {};
    const entry = {};
    if (g.calls?.length) entry.calls = g.calls;
    if (g.used_by?.length) entry.used_by = [...new Set(g.used_by)];
    if (g.deps?.length) entry.deps = g.deps;
    if (g.implements?.length) entry.implements = g.implements;
    if (g.implemented_by?.length) entry.implemented_by = [...new Set(g.implemented_by)];
    if (node.rules?.length) entry.rules = node.rules;
    entry.kind = node.kind;
    entry.status = node.status || 'implemented';
    if (node.module) entry.module = node.module;
    entry.source = node._source;
    graphOut[id] = entry;
  }

  // Backlog: every open change/bug, with targets + conflicts.
  const targetOwners = new Map(); // nodeId -> [changeId]
  for (const c of model.changes) {
    for (const d of c.deltas) {
      if (!d.target) continue;
      if (!targetOwners.has(d.target)) targetOwners.set(d.target, []);
      targetOwners.get(d.target).push(c.id);
    }
  }
  const backlog = model.changes
    .filter((c) => (c.meta.status || 'planned') !== 'implemented')
    .map((c) => {
      const targets = [...new Set(c.deltas.map((d) => d.target).filter(Boolean))];
      const conflicts = [];
      for (const t of targets) {
        const others = (targetOwners.get(t) || []).filter((x) => x !== c.id);
        for (const o of others) if (!conflicts.includes(o)) conflicts.push(o);
      }
      return {
        id: c.id,
        type: c.meta.type || 'feature',
        title: c.meta.title || c.id,
        owner: c.meta.owner || 'unassigned',
        status: c.meta.status || 'planned',
        current_step: c.plan?.current_step ?? null,
        targets,
        conflicts,
      };
    });

  const index = {
    generated_at: new Date().toISOString(),
    source_hash: hashMap(projectDir),
    totals,
    status_rollup,
    graph: graphOut,
    backlog,
  };

  writeFileSync(join(projectDir, 'map', 'index.yaml'), yaml.dump(index, { lineWidth: 120, sortKeys: false }), 'utf8');
  writeFileSync(join(projectDir, 'status.md'), renderStatus(model, index, byKind), 'utf8');
  return { model, index };
}

function renderStatus(model, index, byKind) {
  const lines = [];
  const date = index.generated_at.slice(0, 10);
  lines.push(`# System Status`);
  lines.push('');
  lines.push(`> Generated by \`roya index\` on ${date}. Never hand-edit — run \`npm run status\`.`);
  lines.push('');

  // Implemented summary line per kind that has a status rollup.
  lines.push('## Now implemented');
  lines.push('');
  lines.push('| Kind | Implemented | Partial | Planned | Deferred | Total |');
  lines.push('|------|-------------|---------|---------|----------|-------|');
  for (const [kind, r] of Object.entries(index.status_rollup)) {
    const total = index.totals[kind];
    lines.push(`| ${kind} | ${r.implemented || 0} | ${r.partial || 0} | ${r.planned || 0} | ${r.deferred || 0} | ${total} |`);
  }
  lines.push('');

  // Backlog board (features + bugs, one place).
  lines.push('## Backlog (pending work — features + bugs)');
  lines.push('');
  if (index.backlog.length === 0) {
    lines.push('_Nothing pending._');
  } else {
    lines.push('| ID | Type | Title | Owner | Status | Step | Touches | Conflict |');
    lines.push('|----|------|-------|-------|--------|------|---------|----------|');
    for (const b of index.backlog) {
      const step = b.current_step != null ? String(b.current_step) : '—';
      const touches = b.targets.join(', ') || '—';
      const conflict = b.conflicts.length ? b.conflicts.join(', ') : '—';
      lines.push(`| ${b.id} | ${b.type} | ${b.title} | ${b.owner} | ${b.status} | ${step} | ${touches} | ${conflict} |`);
    }
  }
  lines.push('');

  // Partial / deferred with reasons.
  const flagged = byKind
    ? [...model.nodes.values()].filter((n) => n.status === 'partial' || n.status === 'deferred')
    : [];
  if (flagged.length) {
    lines.push('## Partial / deferred (with reason)');
    lines.push('');
    lines.push('| ID | Kind | Status | Reason |');
    lines.push('|----|------|--------|--------|');
    for (const n of flagged) {
      lines.push(`| ${n.id} | ${n.kind} | ${n.status} | ${n.reason || '—'} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
